### ISSUE TITLE
[CRASH] VPN: specialized Unsignedinteger<>.init<A>(_:)

### ISSUE THREAD

**Issue by Grachev-KA** [shineRR/pingx#3]
Good afternoon. I received the following error in the application. Can you help?

![iScreen Shoter - 20240606222136360](https://github.com/shineRR/pingx/assets/76969375/60c4bedc-f4e6-4d33-8b68-5b32b044185a)

**Comment by shineRR** [comment]
@Grachev-KA 
Hi, You can try out the new version (v1.0.5). If it works for you, we can close the issue. Please update as soon as possible. Thanks!

**Comment by shineRR** [comment]
Please reopen this issue if you encounter it again. 
Fixed in v1.0.5
